In [1]:
import pandas
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

In [2]:
df = pandas.read_csv("sample_data.csv")
df.head()

   ID         Car    Car Model  Volume  Weight  CO2
0   1   Chevrolet  Car Model 1    1872    1692   91
1   2      Nissan  Car Model 2    1366     874  141
2   3  Oldsmobile  Car Model 3    1753    1826  147
3   4      Jaguar  Car Model 4    1761     970   92
4   5        Audi  Car Model 5    1616    1376  135

In [3]:
X=df[['Weight','Volume']]

scaledX=scale.fit_transform(X)

print(scaledX)

[[ 9.93406911e-01  6.22159805e-01]
 [-1.26618016e+00 -5.04895967e-01]
 [ 1.36355932e+00  3.57101234e-01]
 [-1.00099635e+00  3.74920298e-01]
 [ 1.20510194e-01  5.19497700e-02]
 [ 1.41604361e+00 -1.50742078e-03]
 [ 1.16743379e+00  5.30837104e-01]
 [-2.30305891e-01  4.30604871e-01]
 [ 1.42433061e+00 -1.39139438e+00]
 [-1.44573170e+00 -1.51167306e+00]
 [ 6.75738802e-01 -4.46984011e-01]
 [ 1.54863552e+00 -1.84152823e-01]
 [ 1.21991808e+00 -6.49675859e-01]
 [ 1.41051895e+00 -1.75445780e+00]
 [-6.75041243e-01 -1.11297151e+00]
 [ 1.23372974e+00 -1.38248485e+00]
 [ 5.62483215e-01  1.47747486e+00]
 [-1.56451195e+00 -4.22482798e-01]
 [ 1.82763099e+00  6.24387188e-01]
 [-5.47974000e-01  5.44201402e-01]
 [-5.09301361e-01 -5.71717456e-01]
 [ 1.53658171e-01 -7.40998560e-01]
 [ 1.83591798e+00  1.33937711e+00]
 [-1.07005463e+00 -1.53171951e+00]
 [-1.45125636e+00 -1.62526959e+00]
 [ 3.21155901e-02 -8.10047431e-01]
 [ 1.16743379e+00  6.02113358e-01]
 [-2.60691536e-01 -8.90233217e-01]
 [-6.22556947e-01  9.76313694e-01]
 [ 8.91200650e-01  6.37751486e-01]
 [ 3.76402529e-02  1.10772929e+00]
 [ 1.26687772e+00  1.11218405e+00]
 [ 9.82357585e-01  1.02754350e+00]
 [-5.03776698e-01  2.74485576e-02]
 [ 4.40940634e-01 -1.75000304e+00]
 [-1.19812636e-01 -3.71252990e-01]
 [-1.72748950e+00 -4.62575691e-01]
 [ 1.03760421e+00 -1.44707895e+00]
 [ 2.72438420e-01  3.39282170e-01]
 [-7.00906710e-02 -1.32457289e+00]
 [-6.44655598e-01  6.48888400e-01]
 [-4.48530070e-01 -1.64531604e+00]
 [-4.89965041e-01 -7.72384410e-02]
 [-7.00906710e-02 -3.17795800e-01]
 [ 3.08348728e-01  4.30402382e-02]
 [-3.14180317e-02 -1.57849455e+00]
 [ 4.87900268e-01 -1.79698057e-01]
 [ 6.20492174e-01  5.88749061e-01]
 [-6.69516581e-01  1.26587348e+00]
 [-8.26969469e-01  1.15227695e+00]
 [ 1.04865354e+00 -2.55429077e-01]
 [-1.13358825e+00 -1.20874898e+00]
 [ 1.32764901e+00 -1.66981725e+00]
 [-1.60594692e+00 -1.67872678e+00]
 [ 7.08886778e-01  1.16543876e-01]
 [-2.10969571e-01 -2.97749353e-01]
 [ 1.23272526e-01  1.62448213e+00]
 [ 7.39272424e-01  1.86058472e+00]
 [-1.14463758e+00  9.82995843e-01]
 [-2.44117548e-01 -1.55196844e-01]
 [-2.66216199e-01 -7.29861645e-01]
 [-1.46783035e+00  1.81137981e-01]
 [ 4.16079652e-01  3.85854723e-02]
 [-8.93265423e-01  6.13250273e-01]
 [ 1.65912877e+00  1.09436499e+00]
 [-3.26987489e-01 -2.57656460e-01]
 [ 1.63979245e+00 -1.31343598e+00]
 [ 5.62483215e-01  7.71394463e-01]
 [ 5.01711925e-01  1.59107139e+00]
 [ 1.86806147e-01 -1.66090772e+00]
 [-1.49821599e+00  1.57325232e+00]
 [-1.28827881e+00  1.45965579e+00]
 [ 1.70332608e+00  1.23246273e+00]
 [-5.45211669e-01  2.41277321e-01]
 [-1.29104114e+00  1.27255563e+00]
 [-8.04870818e-01  8.80536227e-01]
 [-5.75597314e-01  6.57797932e-01]
 [-4.95489704e-01  2.52414235e-01]
 [-8.79453766e-01 -1.90834971e-01]
 [ 4.27128978e-01 -6.98678284e-01]
 [-1.12253893e+00  1.56636769e-01]
 [-1.69534601e-01  1.00749706e+00]
 [-2.58933689e-02 -1.99744503e-01]
 [-1.31313979e+00 -7.50110581e-02]
 [-4.67866390e-01  1.07654593e+00]
 [-1.40705906e+00  1.94968004e+00]
 [-1.30485280e+00  5.44201402e-01]
 [ 4.57514623e-01 -7.98910517e-01]
 [ 1.30555036e+00  6.77844379e-01]
 [-8.02108487e-01 -1.75000304e+00]
 [ 5.42142411e-02  8.75878972e-02]
 [-9.76135364e-01  6.02113358e-01]
 [ 2.36528112e-01 -1.59854100e+00]
 [-1.63909490e+00 -1.46489802e+00]
 [-1.72472717e+00 -2.77702906e-01]
 [ 5.95631192e-01  1.28814731e+00]
 [ 1.79172068e+00  9.13946971e-01]
 [ 1.60664448e+00 -4.46984011e-01]
 [ 2.80725414e-01  7.84758760e-01]]

In [4]:
y=df['CO2']
regr = linear_model.LinearRegression()
regr.fit(scaledX, y)

scaled = scale.transform([[2000, 1200]])

predictCO2 = regr.predict([scaled[0]])
print(predictCO2)

[127.97315167]